/**
 * Staff Forms Type Definitions
 *
 * Type system for the Staff Forms feature - post-event feedback forms
 * sent to staff members assigned to events.
 */

import type { FormField, FormResponses } from './event-forms'

// ===========================================
// STAFF FORM STATUS
// ===========================================

/**
 * Staff form status progression
 * - pending: Form created but not sent
 * - sent: Form link sent to staff member
 * - viewed: Staff member opened the form
 * - completed: Staff member submitted the form
 */
export type StaffFormStatus = 'pending' | 'sent' | 'viewed' | 'completed'

// ===========================================
// STAFF FORM TYPES
// ===========================================

/**
 * Base staff form - matches database schema
 */
export interface StaffForm {
  id: string
  tenant_id: string
  event_id: string
  staff_assignment_id: string
  template_id: string | null
  title: string
  description: string | null
  fields: FormField[]
  public_id: string | null
  responses: FormResponses | null
  status: StaffFormStatus
  sent_at: string | null
  viewed_at: string | null
  completed_at: string | null
  task_id: string | null
  created_at: string
  updated_at: string
}

/**
 * Staff form with related data for display
 */
export interface StaffFormWithRelations extends StaffForm {
  event?: {
    id: string
    title: string
    start_date: string | null
    end_date: string | null
  } | null
  staff_assignment?: {
    id: string
    user_id: string
    users?: {
      id: string
      first_name: string
      last_name: string
      email: string
    }
    staff_roles?: {
      id: string
      name: string
    }
  } | null
  template?: {
    id: string
    name: string
  } | null
}

/**
 * Staff form for creation
 */
export interface StaffFormInsert {
  tenant_id?: string            // Usually set by API
  event_id: string
  staff_assignment_id: string
  template_id?: string | null
  title: string
  description?: string | null
  fields: FormField[]
  public_id?: string            // Usually generated by API
  status?: StaffFormStatus
}

/**
 * Staff form for updates
 */
export interface StaffFormUpdate {
  title?: string
  description?: string | null
  fields?: FormField[]
  responses?: FormResponses | null
  status?: StaffFormStatus
  sent_at?: string | null
  viewed_at?: string | null
  completed_at?: string | null
  task_id?: string | null
}

// ===========================================
// API REQUEST/RESPONSE TYPES
// ===========================================

/**
 * Request to send staff forms
 */
export interface SendStaffFormsRequest {
  event_id: string
  template_id: string
  staff_assignment_ids: string[]  // Specific assignments to send to
}

/**
 * Request to send forms to all staff on an event
 */
export interface SendAllStaffFormsRequest {
  event_id: string
  template_id: string
}

/**
 * Public staff form response (for unauthenticated access)
 */
export interface PublicStaffFormResponse {
  form: {
    id: string
    title: string
    description: string | null
    fields: FormField[]
    status: StaffFormStatus
    responses: FormResponses | null
  }
  event: {
    title: string
    start_date: string | null
  } | null
  staff: {
    name: string
    role: string | null
  } | null
  tenant: {
    name: string
    logoUrl: string | null
  }
}

/**
 * Staff form submission payload
 */
export interface StaffFormSubmissionPayload {
  responses: {
    [fieldId: string]: string | string[] | null
  }
}

// ===========================================
// UI HELPER TYPES
// ===========================================

/**
 * Staff form status with display info
 */
export interface StaffFormStatusInfo {
  status: StaffFormStatus
  label: string
  color: 'gray' | 'yellow' | 'blue' | 'green'
  icon: 'circle' | 'send' | 'eye' | 'check-circle'
}

/**
 * Get display info for staff form status
 */
export function getStaffFormStatusInfo(status: StaffFormStatus): StaffFormStatusInfo {
  const statusMap: Record<StaffFormStatus, StaffFormStatusInfo> = {
    pending: { status: 'pending', label: 'Pending', color: 'gray', icon: 'circle' },
    sent: { status: 'sent', label: 'Sent', color: 'yellow', icon: 'send' },
    viewed: { status: 'viewed', label: 'Viewed', color: 'blue', icon: 'eye' },
    completed: { status: 'completed', label: 'Completed', color: 'green', icon: 'check-circle' },
  }
  return statusMap[status]
}

/**
 * Check if staff form has been submitted
 */
export function isStaffFormCompleted(form: StaffForm): boolean {
  return form.status === 'completed' && form.completed_at !== null
}

/**
 * Summary of staff form completion for an event
 */
export interface StaffFormCompletionSummary {
  total: number
  pending: number
  sent: number
  viewed: number
  completed: number
}

/**
 * Calculate completion summary from staff forms
 */
export function calculateStaffFormSummary(forms: StaffForm[]): StaffFormCompletionSummary {
  return forms.reduce(
    (acc, form) => {
      acc.total++
      acc[form.status]++
      return acc
    },
    { total: 0, pending: 0, sent: 0, viewed: 0, completed: 0 }
  )
}
